### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Jerakin** [Jerakin/Pokedex5E#335]
`filtler` and `reseted`
![image01](https://user-images.githubusercontent.com/5273682/71349277-eb262f80-256e-11ea-9fce-8aafbfb02095.png)
![image0](https://user-images.githubusercontent.com/5273682/71349278-eb262f80-256e-11ea-8a0b-acc3ff21310b.png)

**Comment by krehbielscott** [comment]
appears this issue has been resolved
