### ISSUE TITLE
QR export/import via camera

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#392]
I was fiddling with this but I don't have OSX so I can't test the camera bits.

Here is a QR read/write package:
https://github.com/defold/extension-qrcode/archive/1.1.zip

Here's how a QR code could be generated (though I don't know how to display it yet):
```
	-- qr code can be generated via:
	local buffer, size  = qrcode.generate(pokemonString)
	-- can display buffer onscreen - "The stream name is data and the type+count is UINT8 * 1"
	-- it's square so the dimensions are size * size
```

Here is a Camera package:
https://github.com/defold/extension-camera/archive/master.zip

Some WIP code to read the camera each frame (which I don't know how to do) and read the camera, sending that to the qr decoder, and getting a Pokemon string out:
```
	if camera.start_capture(camera.CAMERA_TYPE_BACK, camera.CAPTURE_QUALITY_HIGH) then

		-- start loop
		
			-- camera buffer should be:
			local info = camera.get_info()
			-- info has width, height

			-- has stream named rgb, type buffer,VALUE_TYPE_UINT8, value count 1
			local buffer = camera.get_frame()

			-- (Could theoretically display this if needed?)

			-- I'm not clear on whether the buffer is in the right format for qrcode, qrcore says it needs "An image buffer where the first stream must be of format UINT8 * 3, and have the dimensions width*height"
			-- but, assuming it does,
			local qrstring = qrcode.scan(buffer, info.width, info.height, 0) -- 0 is flip_x

			if string ~= nil then
				-- qr code found, can exit loop and check if it's a pokemon string
			else
				-- no qr code found
			end

		-- end loop

		camera.stop_capture()
	end
```

**Comment by magroader** [comment]
Note that the QR package doesn't actually compile on Windows, there's an errant header I had to comment out.

**Comment by Jerakin** [comment]
I really like this idea and we should investigate it futher 
Questions to answer  
- [ ] How much data can we "pass" with a QR code (and will #418 help)
- [ ] Does it have iOS Support
- [ ] Does it have Android Support
- [ ] How should we handle html5
- [ ] Is it possible to dev it on Windows

**Comment by Jerakin** [comment]
I can create the QR code just fine on OSX and Android but loading it leaves a lot to be desired.

I can not get the `extension-camera` to run tried Android and OSX. I created an issue for it https://github.com/defold/extension-camera/issues/3 unfortunately I don't know C++ so I can't fix it myself but will have to wait for someone on Defolds end to pick it up.

My test is in the branch `392_share_with_QR`
