### ISSUE TITLE
Removing penalty for feats

### ISSUE THREAD

**Issue by Stafruit** [Jerakin/Pokedex5E#441]
If you attach extra move to a pokemon it gives you -2 stat points even though that wasn't in  (when I looked) the rules in the phb, so why's it a thing now?

**Comment by Jerakin** [comment]
The PHB says
> the following D&D 5e features can be selected for Pokémon **instead of taking the Ability Score Increase** given during the leveling process.

A feat can be taken _instead_ if a ASI increase, which is 2 points. So if you pick a feat your ASI point poll will go down by 2.

**Comment by Stafruit** [comment]
Alright well if nothing else thanks for clearing that up for me.
