### ISSUE TITLE
Evolving a pokemon does not mark the evolution as "caught" in the Pokedex

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#465]
https://discordapp.com/channels/527605327303147520/562710992753131521/732266142688608407

**Comment by Jerakin** [comment]
Can not reproduce this. Will ask the reporter if he got a repro case

**Comment by Jerakin** [comment]
User could not reproduce either. Closing as it until we get another user reporting it as without a repro the sample size is too small.
