### ISSUE TITLE
Trainer attribute edits does not save

### ISSUE THREAD

**Issue by Jerakin** [Jerakin/Pokedex5E#483]

**Comment by Jerakin** [comment]
Can't reproduce on windows. Will have to investigate whey it doesn't get saved, it should be saved in the `final` function

**Comment by magroader** [comment]
Is it possible final never gets called for phones? There’s not really a point where you exit the app.

**Comment by Jerakin** [comment]
If I haven't misunderstood something I think that when you do `monarch.back` it should unload the scene and therefore call the `final`

**Comment by Jerakin** [comment]
I can no longer reproduce this on device either. Will close and reopen if the issue resurfaces.
