### ISSUE TITLE
Bugs: Various issues with STAB

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#515]
https://discordapp.com/channels/527605327303147520/562710992753131521/739643162930184203

Sounds like:

- Shadow sneak /will-o-wisp not showing AB
- Stab sneak not showing stab properly
- Fire STAB added to shadow claw but not ember
- STAB maybe being added to Struggle when it shouldn't?

**Comment by Jerakin** [comment]
Fixed at 3085fe601fd30a953cbec64bd7f3c370345695c5
