### ISSUE TITLE
Enhancement: Pumpkaboo / Gourgeist variants

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#523]
https://discordapp.com/channels/527605327303147520/562710992753131521/739881108136656906

I think keeping the current "Small" version as-is, and adding 3 "new" pokemon with subtly different stats, may be the way to go. However, we'd want to make sure that future changes to Pumpaboo affect all variants. Maybe pokemon should have optional "modifier" versions that apply on top a base template?

e.g.:
```
"pumpkaboo":
{
  name: "Pumpkaboo (Small)",
  str: 6,
  dex: 7,
  con: 8,
  wis: 9,
  cha: 10,
  int: 11,
  moves: [...],
  evolutions: ,
  ...
},
"pumpkaboo-average":
{
  template: "pumpkaboo",
  dex: 6,
  con: 9,
  name: "Pumpkaboo (Average)",
},
"pumpkaboo-large":
{
  template: "pumpkaboo",
  dex: 5,
  con: 10,
  name: "Pumpkaboo (Large)",
},
```
Where the variants (which reference the templates) just have overrides.

Alternative idea:
```
"pumpkaboo":
{
  name: "Pumpkaboo",
  str: 6,
  dex: 7,
  con: 8,
  wis: 9,
  cha: 10,
  int: 11,
  variants: {
      {
          name: "Small",
      },
      {
        dex: 6,
         con: 9,
          name: "Average",
      },
      {
        dex: 5,
         con: 10,
          name: "Large",
      },
  }
},
```
And then when you're adding a pokemon, if variants are found they could be displayed and you would pick one.

This could also work for Wormadam.

**Comment by Jerakin** [comment]
There are a lot of Pokemon this could be used on, here is a list of the ones I could think of for future reference.
* Pumpkaboo
* Gourgeist
* Arceus
* Wormadam
* Zygarde
* Kyurem
* Shaymin
* Rotom
* Meloetta
* Hoopa
* Giratina
* Castform

A system like this could also be extended into be used for a "transform" system. Where you can change forms temporarily on the Pokemon.

We wouldn't want to maintain this by hand so we would need to change the converting script to be smart enough to set up the json as forms (probably defined in a json script?)

**Comment by magroader** [comment]
Would this also be a good way to do Alolan and Galarian forms? I'm not sure how those differ from these, if at all. Those are determined by the individual and can't be changed afterward... maybe these could be transformable after creation or not based on a flag?

**Comment by Jerakin** [comment]
We could have "regional variants" as a sub type you can choose while creating a pokemon.

It would be a good way to do "Mega Evolution", "Gigantamax" and "Dynamax"

**Comment by magroader** [comment]
New idea that allows for sizing and region-based stuff. These variants would be entirely dynamic, so further variants would be easy to add in the future (like, all the Unown variants would be easy to do with this):
```
{
    ...
    variants: {
        Size: {
            Large: {
                dex: 8,
                con: 12
            },
            Small: {
                dex: 12,
                con: 8
            }
        },
        Region: {
            Default: {
               types: ["Fire"]
            },
            Galar: {
               types: ["Ice"]
            }
        }
    }
}
```
This could be further enhanced to allow for variants that need to be changed from the Edit screen (region/size) versus things that could be changed from the main party screen (mega evolution, dynamax, gigantamax).

**Comment by Jerakin** [comment]
## Pumpkaboo
**Decided at:** combat/discovery 
**Type:** Permanent
**Changes:** Size, attributes(DEX and CON)

## Gourgeist
**Decided at:** combat/discovery/pre-evolution
**Type:** Permanent
**Changes:** Size, attributes(DEX and CON)

## Arceus
**Decided at:** Item change
**Type:** Static
**Changes:** Typing, signature move

## Wormadam
**Decided at:** evolved from Burmy or combat/discovery
**Type:** Permanent
**Changes:** Typing, move set, attributes


## Zygarde
**Decided at:** HP change
**Type:** Static
**Changes:** Size, attributes

## Kyurem

## Shaymin
**Decided at:** Item change
**Type:** Static
**Changes:** attributes, move set

## Rotom
**Decided at:** Item change
**Type:** Static
**Changes:** attributes, signature move/ability



## Meloetta
**Decided at:** Move usage
**Type:** Static
**Changes:** typing, abilities


## Hoopa
**Decided at:** Item change
**Type:** Static
**Changes:** typing, size, attributes, move set

## Giratina
**Decided at:** Item change
**Type:** Static
**Changes:** size, attributes

## Castform
**Decided at:** Weather
**Type:** Temporary
**Changes:** typing

**Comment by magroader** [comment]
Another idea for the data layout, in a way that fits with the data we get from Joe:

```
[
{
  "name" : "Pumpkaboo",
  "forms" : {
      { "name" : "Pumkaboo - Small", "formName" : "Small", isDefault: true },
      { "name" : "Pumkaboo - Average", "formName" : "Average" },
      { "name" : "Pumkaboo - Large", "formName" : "Large" },
      { "name" : "Pumkaboo - Supersize", "formName" : "Supersize" },
    ]
},
{
  "name" : "Rotom",
  "forms" : {
      { "name" : "Rotom", "formName" : "Regular", isDefault: true },
      { "name" : "Rotom Heat", "formName" : "Heat" },
      { "name" : "Rotom Wash", "formName" : "Wash" },
      { "name" : "Rotom Frost", "formName" : "Frost" },
      { "name" : "Rotom Fan", "formName" : "Fan" },
      { "name" : "Rotom Mow", "formName" : "Mow" },
    ]
},
...
]
```
