### ISSUE TITLE
CRASH: Looking at a Pokemon with Withdraw crashes app

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#526]
1. Add Grotle to party
1. Tap on Grotle to view them

This will crash due to the move Withdraw. A breakpoint in `pokemon.lua` here:

```
function M.get_move_data(pokemon, move_name)
	local move = movedex.get_move_data(move_name)
	local dmg, mod, stab = get_damage_mod_stab(pokemon, move)
	local requires_save = move.Save ~= nil
```

`mod` in this case is `nil`. Later on, it is used in some arirthmetic:
```
	if move.atk == true and not move.autohit then
		move_data.AB = mod + M.get_proficency_bonus(pokemon) + trainer.get_attack_roll() + trainer.get_move_type_attack_bonus(move_data.type) + trainer.get_pokemon_type_attack_bonus(M.get_type(pokemon))
	end
```

I suspect `mod` should be returning 0 from `get_damage_mod_stab` here, so my guess is there's an error in that function that it can return `nil` for `mod`.

**Comment by Jerakin** [comment]
Fixed in c74e7fb327c6062319336d548d5e69e5428d11f2
