### ISSUE TITLE
Fakemon are no longer overwriting existing Pokemon

### ISSUE THREAD

**Issue by Jerakin** [Jerakin/Pokedex5E#535]

**Comment by magroader** [comment]
I may have fixed this in the generation VII branch - what were the symptoms? I was seeing duplicate pokemon NAMES when adding a new pokemon (e.g. Rattata listed twice). Is that what this was about?

**Comment by Jerakin** [comment]
Wish I had written a discription for it. But I think that was it, will close this and create a new issue if similar thing arrise.
