### ISSUE TITLE
Update natures for new wording

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#597]
- Cocky -> Arrogant
- Dumb -> Innocent

This will require a data update for each pokemon. Fortunately, I've been working on just such a system for variants!

**Comment by Jerakin** [comment]
We will only need to update the name of the nature, if I recall correctly the save data contains the name but also the increase in attributes. I think that if we simply changed the name it would only visually be incorrect (still say Cocky instead of Arrogant if you had Cocky to begin with).
