### ISSUE TITLE
Bug (master): Exception when moving PC pokemon to party

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#622]
This is happening with current latest in master

* Create new profile
* Add 4 pokemon (3 to party, 1 to PC)
* Go to PC
* Move the PC pokemon to the party
* Choose a party pokemon to replace

Results in exception:
```
ERROR:SCRIPT: /pokedex/storage.lua:77: attempt to compare nil with number
stack traceback:
	/pokedex/storage.lua:77: in function </pokedex/storage.lua:77>
	[C]: in function 'sort'
	/pokedex/storage.lua:42: in function 'list_of_ids_in_party'
	/screens/storage/inventory.lua:38: in function 'setup'
	/screens/storage/inventory.lua:28: in function 'redraw'
	/screens/storage/storage.gui_script:147: in function </screens/storage/storage.gui_script:135>
ERROR:GAMESYS: Error when dispatching message to gui scene: -2. Message 'party_updated' sent from main:/collection21/go#gui to main:/collection20/go#gui.
```

If you then view the profile screen, the profile will show 4 pokemon (which should not be possible as the default max party size is 3).

This was confusing issues for my feature/581_more_pokemon_variants branch. I thought I had caused it! :D

**Comment by Jerakin** [comment]
https://github.com/Jerakin/Pokedex5E/issues/595

**Comment by Jerakin** [comment]
This were introduced in a01a6043 where I said "slots can't be nil" apparently slots can totally be nil
