### ISSUE TITLE
Change in HP in existing Pokemon

### ISSUE THREAD

**Issue by joethedm** [Jerakin/Pokedex5E#676]
The HP of most of my existing Pokemon is different than what it was before the update. Some went up and some went down. If I recreate the pokemon from scratch, their resulting HP gets to the correct amount - so it's just the ones that were already in the app when I updated.

**Comment by magroader** [comment]
Do you have an example of one that changed? Can you copy+paste the pokemon into this bug so we can try to import the pokemon for testing?

**Comment by joethedm** [comment]
Original pokemon that went down by 11:
{"abilities":["Guts","Flame Body"],"attributes":{"CHA":0,"CON":1,"DEX":1,"INT":0,"STR":0,"WIS":0,"custom":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0},"increased":{"CHA":0,"CON":6,"DEX":4,"INT":0,"STR":0,"WIS":0},"nature":{"DEX":2,"WIS":-2}},"exp":0,"feats":["Tough"],"gender":2,"hp":{"current":95,"edited":false,"max":47},"id":"00c5944d99756f7adc9ea0083b117b75","level":{"caught":4,"current":8,"evolved":[6]},"location":1,"loyalty":1,"moves":{"Ember":{"index":1,"pp":15},"Flail":{"index":2,"pp":10},"Peck":{"index":4,"pp":20},"Quick Attack":{"index":3,"pp":15}},"nature":"Clumsy","nickname":"Cinder","number":7,"slot":2,"species":{"caught":"Fletchling","current":"Fletchinder"},"statuses":[],"version":7}

Remade pokemon after the update:
{"abilities":[],"attributes":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0,"custom":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0},"increased":{"CHA":0,"CON":7,"DEX":5,"INT":0,"STR":0,"WIS":0},"nature":{"DEX":2,"WIS":-2}},"exp":0,"feats":["Tough"],"gender":2,"hp":{"current":106,"edited":false,"max":58,"temp":0},"id":"126cc007831911d4f32aada703bfdb26","level":{"caught":1,"current":8,"evolved":[6]},"location":1,"loyalty":1,"moves":{"Ember":{"index":1,"pp":15},"Flail":{"index":4,"pp":10},"Peck":{"index":3,"pp":20},"Quick Attack":{"index":2,"pp":15}},"nature":"Clumsy","number":9,"slot":4,"species":{"caught":"Fletchling","current":"Fletchinder"},"statuses":[],"version":7}

**Comment by magroader** [comment]
The caught level went from 4 to 1, might that have anything to do with it? Also abilities guts / flame body vs. nothing.

**Comment by joethedm** [comment]
I noticed in the new version of the app there is no option to level a pokemon as soon as you catch it - you have to add to party and then edit.

In the old version of the app, I updated the level to 4 before adding to party.

**Comment by joethedm** [comment]
but here's another example, both caught at level 1: HP changed by +1
{"abilities":["Sturdy","Guts"],"attributes":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0,"custom":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0},"increased":{"CHA":0,"CON":7,"DEX":0,"INT":0,"STR":6,"WIS":0},"nature":{"CHA":-2,"STR":2}},"exp":0,"feats":["Savage Attacker"],"gender":1,"hp":{"current":134,"edited":false,"max":74},"id":"b5fb9d3f4e53eba6c85eebc1d4252e0a","level":{"caught":1,"current":10,"evolved":[8]},"location":1,"loyalty":3,"moves":{"Iron Head":{"index":2,"pp":10},"Mud-Slap":{"index":3,"pp":5},"Protect":{"index":1,"pp":3},"Rock Tomb":{"index":4,"pp":10}},"nature":"Arrogant","nickname":"Bud","number":1,"slot":0,"species":{"caught":"Aron","current":"Lairon"},"statuses":[],"version":7}

{"abilities":["Guts","Sturdy"],"attributes":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0,"custom":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0},"increased":{"CHA":0,"CON":7,"DEX":0,"INT":0,"STR":6,"WIS":0},"nature":{"CHA":-2,"STR":2}},"exp":0,"feats":["Savage Attacker"],"gender":1,"hp":{"current":132,"edited":false,"max":72,"temp":0},"id":"ebf17d44ea8ddbb8e360ddbc0765bde9","level":{"caught":1,"current":10,"evolved":[8]},"location":1,"loyalty":3,"moves":{"Harden":{"index":1,"pp":5},"Mud-Slap":{"index":3,"pp":5},"Tackle":{"index":2,"pp":20}},"nature":"Arrogant","number":10,"slot":5,"species":{"caught":"Aron","current":"Lairon"},"statuses":[],"version":7}

**Comment by joethedm** [comment]
I actually have the code for both pokemon as it was before I updated at all because I had to send them to our DM.

{"level":{"evolved":[8],"caught":1,"current":10},"id":"b5fb9d3f4e53eba6c85eebc1d4252e0a","nickname":"Bud","feats":["Savage Attacker"],"abilities":["Sturdy","Guts"],"hp":{"max":72,"edited":false,"current":132},"slot":0,"statuses":[],"number":1,"species":{"caught":"Aron","current":"Lairon"},"gender":1,"exp":0,"attributes":{"nature":{"STR":2,"CHA":-2},"CON":0,"CHA":0,"INT":0,"STR":0,"increased":{"CON":7,"CHA":0,"STR":6,"INT":0,"WIS":0,"DEX":0},"WIS":0,"DEX":0},"loyalty":3,"moves":{"Protect":{"pp":3,"index":1},"Rock Tomb":{"pp":10,"index":4},"Mud-Slap":{"pp":5,"index":3},"Iron Head":{"pp":10,"index":2}},"nature":"Cocky"}
{"level":{"evolved":[6],"caught":4,"current":8},"id":"00c5944d99756f7adc9ea0083b117b75","hp":{"max":58,"edited":false,"current":106},"feats":["Tough"],"abilities":["Guts","Flame Body"],"loyalty":1,"slot":2,"statuses":[],"number":7,"species":{"caught":"Fletchling","current":"Fletchinder"},"gender":2,"exp":0,"attributes":{"CON":1,"CHA":0,"DEX":1,"INT":0,"STR":0,"increased":{"CON":6,"CHA":0,"STR":0,"INT":0,"WIS":0,"DEX":4},"WIS":0,"nature":{"WIS":-2,"DEX":2}},"nickname":"Cinder","moves":{"Quick Attack":{"pp":15,"index":3},"Peck":{"pp":20,"index":4},"Ember":{"index":1,"pp":15},"Flail":{"index":2,"pp":10}},"nature":"Clumsy"}

**Comment by magroader** [comment]
Awesome, thanks for all this detail. This should really help narrow in on what the problem is.

If you were to do this by hand, you think the max of 58 is correct?

**Comment by joethedm** [comment]
Fletchling 1 to Fletchinder 8, evolving at level 6.

16 base HP (level 1) + 4*4 (average of d6 hit dice at levels 2, 3, 4, and 5) + 6*2 (double level for evolving at level 6) + 5*3 (average of new d8 hit dice for levels 6, 7, and 8) + 4*8 (18 CON score retroactive for all 8 levels) + 2*8 (Tough Feat) = 107

You all are getting to 106 because you take the average of the prior evolution hit dice before evolving, when it should get the new hit dice at the evolution level, per the rules. It will always be a minor 1/2 HP difference so not a big deal.

I don't know why it says a max of 58, unless some of the calcs above aren't included in the HP section of whatever you have behind the scenes.

**Comment by joethedm** [comment]
I'm guessing CON score increases and Tough Feat aren't included in that 58, because without those I get to 59, and that's because of the hit dice thing I mentioned.

**Comment by krehbielscott** [comment]
Had an Azumarill before the update. After the update that Azumarill has 176 HP.

Recreated the Azumarill with identical stats after the update and that version has 173 hp. 

Original Azumarill:
{"abilities":["Thick Fat","Sap Sipper"],"attributes":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0,"custom":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0},"increased":{"CHA":0,"CON":2,"DEX":7,"INT":0,"STR":5,"WIS":2},"nature":{"CHA":-2,"DEX":2}},"exp":174216,"feats":["Tough","Hidden Ability"],"gender":2,"hp":{"current":176,"edited":false,"max":113,"temp":0},"id":"ff235c48e46860c1d3c491bda2477f64","level":{"caught":1,"current":14,"evolved":[3,6]},"location":1,"loyalty":2,"moves":{"Aqua Ring":{"index":2,"pp":5},"Bubble Beam":{"index":3,"pp":10},"Helping Hand":{"index":1,"pp":5},"Play Rough":{"index":4,"pp":5}},"nature":"Energetic","nickname":"Milly","number":5,"slot":1,"species":{"caught":"Azurill","current":"Azumarill"},"statuses":[],"version":7}

Newly created Azumarill:
{"abilities":["Sap Sipper","Thick Fat"],"attributes":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0,"custom":{"CHA":0,"CON":0,"DEX":0,"INT":0,"STR":0,"WIS":0},"increased":{"CHA":0,"CON":2,"DEX":7,"INT":0,"STR":5,"WIS":2},"nature":{"CHA":-2,"DEX":2}},"exp":0,"feats":["Tough","Hidden Ability"],"hp":{"current":173,"edited":false,"max":110,"temp":0},"id":"90738265d8ec58e0a90e85b140a13da3","level":{"caught":1,"current":14,"evolved":[3,6]},"location":1,"loyalty":2,"moves":{"Splash":{"index":1,"pp":20},"Tail Whip":{"index":3,"pp":15},"Water Gun":{"index":2,"pp":15}},"nature":"Energetic","number":132,"slot":3,"species":{"caught":"Azurill","current":"Azumarill"},"statuses":[],"version":7}
