### ISSUE TITLE
Fakemon Regigi can't evolve into anything

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#706]
I found out the reason is because Regigi has `move=""` defined, so it can only evolve if it has a move named <empty string>.

Alternatively, could change this in pokedex.lua:

```
function M.get_evolution_possible(pokemon, gender, moves)
	local d = M.get_evolution_data(pokemon)
	local gender_allow = false
	local move_allow = true
	if d and d.move then
```
Change that last line to:
```
	if d and d.move and d.move ~= "" then
```

I'm not 100% sure what the intent was here - if the code is at fault, the Fakemon creator is at fault, or the data is at fault, so I'll leave it to @Jerakin .

**Comment by Jerakin** [comment]
Probably the creators fault. But I don't think there is a harm in fixing it in both places just in case. What do you think?

**Comment by magroader** [comment]
I think it's fine to fix in the app so long as there's no valid reason for the move field to be ""
