### ISSUE TITLE
Removing skill from Edit screen does not remove skill from Traits

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#709]
* Have a Vulpix
* Go to Edit screen
* Add the Intimidation skill
* Save
* Check Traits, notice Intimidation
* Go to Edit screen
* Remove the Intimidation skill
* Save
* **Notice Intimidation still under Traits**
* Go to Edit screen
* Attempt to add Skill
* **Notice Intimidation not in list**

Found when looking into #699 (which I could not reproduce)

**Comment by Jerakin** [comment]
I tried to reproduce #699 for about half an hour yesterday too but without success
