### ISSUE TITLE
Losing HP

### ISSUE THREAD

**Issue by jphiliber** [Jerakin/Pokedex5E#737]
Suggestion
You can add temporary HP when you keep the + button press. Is it possible to do the same thing for the HP loose on a hit?
It would be fun to write -23 (like on XP) beside press de - button 23 times, with the risk to press the statuts button that is really close.
Thanks

**Comment by magroader** [comment]
You can tap the HP bar and type -21. Try it out and let us know how it works!

**Comment by jphiliber** [comment]
It worked. Thank you for rapid return

Jean-Philippe Bergeron

Le 30 déc. 2020 à 13:36, Colin C. <notifications@github.com> a écrit :

﻿

You can tap the HP bar and type -23. Try it out and let us know how it works!
