### ISSUE TITLE
Android bundle failing

### ISSUE THREAD

**Issue by MicroWaWe52** [Jerakin/Pokedex5E#769]
I've been having issues building the project for Android right after cloning, I've put the log from building below. The Windows build works just fine, and I've tried to bundle it for Android on both Windows and ubuntu, without success.
Is there a specific defold version or some changes that I should do to build it?

[log.txt](https://github.com/Jerakin/Pokedex5E/files/11365473/log.txt)

**Comment by Jerakin** [comment]
A dependency was out of date. Fixed in https://github.com/Jerakin/Pokedex5E/commit/dfac73190489af4bc751a0fa92fb1b035df89219
